---@type LazySpec
return {
	{ "AstroNvim/astrocommunity" },
	{ import = "astrocommunity.colorscheme.tokyonight-nvim" },
	{ import = "astrocommunity.color.ccc-nvim" },
	{ import = "astrocommunity.color.nvim-highlight-colors" },
	{ import = "astrocommunity.color.twilight-nvim" },
	{ import = "astrocommunity.color.headlines-nvim" },
	{ import = "astrocommunity.editing-support.todo-comments-nvim" },
	{ import = "astrocommunity.editing-support.rainbow-delimiters-nvim" },
	{ import = "astrocommunity.editing-support.nvim-regexplainer" },
	{ import = "astrocommunity.pack.lua" },
	{ import = "astrocommunity.pack.toml" },
	{ import = "astrocommunity.pack.json" },
	{ import = "astrocommunity.pack.rust" },
	{ import = "astrocommunity.pack.go" },
	{ import = "astrocommunity.pack.python-ruff" },
	{ import = "astrocommunity.pack.prisma" },
	{ import = "astrocommunity.pack.tailwindcss" },
	-- { import = "astrocommunity.pack.gleam" },
	{ import = "astrocommunity.pack.docker" },
	{ import = "astrocommunity.pack.astro" },
	{ import = "astrocommunity.pack.crystal" },
	{ import = "astrocommunity.pack.typescript" },
	{ import = "astrocommunity.pack.vue" },
	{ import = "astrocommunity.pack.nim" },
	{ import = "astrocommunity.pack.yaml" },
	{ import = "astrocommunity.lsp.garbage-day-nvim" },
	{ import = "astrocommunity.lsp.lsp-signature-nvim" },
	{ import = "astrocommunity.lsp.ts-error-translator-nvim" },
	{ import = "astrocommunity.code-runner.overseer-nvim" },
	{ import = "astrocommunity.project.nvim-spectre" },
	{ import = "astrocommunity.terminal-integration.flatten-nvim" },
	{ import = "astrocommunity.syntax.hlargs-nvim" },
	{ import = "astrocommunity.fuzzy-finder.telescope-zoxide" },
	-- import/override with your plugins folder
	{ import = "plugins" },
}
