#!/bin/sh
#
# Usage:
#
#    sh install.sh
#
# Environment variables: VERBOSE, CP, LN, MKDIR, RM, DIRNAME.
#
#    env VERBOSE=1 sh install.sh
#
# DO NOT EDIT THIS FILE
# 
# This file is generated by rcm(7) as:
#
#   rcup -B 0 -g
#
# To update it, re-run the above command.
#
: ${VERBOSE:=0}
: ${CP:=/bin/cp}
: ${LN:=/bin/ln}
: ${MKDIR:=/bin/mkdir}
: ${RM:=/bin/rm}
: ${DIRNAME:=/usr/bin/dirname}
verbose() {
  if [ "$VERBOSE" -gt 0 ]; then
    echo "$@"
  fi
}
handle_file_cp() {
  if [ -e "$2" ]; then
    printf "%s " "overwrite $2? [yN]"
    read overwrite
    case "$overwrite" in
      y)
        $RM -rf "$2"
        ;;
      *)
        echo "skipping $2"
        return
        ;;
    esac
  fi
  verbose "'$1' -> '$2'"
  $MKDIR -p "$($DIRNAME "$2")"
  $CP -R "$1" "$2"
}
handle_file_ln() {
  if [ -e "$2" ]; then
    printf "%s " "overwrite $2? [yN]"
    read overwrite
    case "$overwrite" in
      y)
        $RM -rf "$2"
        ;;
      *)
        echo "skipping $2"
        return
        ;;
    esac
  fi
  verbose "'$1' -> '$2'"
  $MKDIR -p "$($DIRNAME "$2")"
  $LN -sf "$1" "$2"
}
handle_file_ln "/home/taskylizard/.dotfiles/README.md" "/home/taskylizard/.README.md"
handle_file_ln "/home/taskylizard/.dotfiles/bin/ls.cr" "/home/taskylizard/.bin/ls.cr"
handle_file_ln "/home/taskylizard/.dotfiles/config/BetterDiscord/themes/zen.theme.css" "/home/taskylizard/.config/BetterDiscord/themes/zen.theme.css"
handle_file_ln "/home/taskylizard/.dotfiles/config/alacritty/alacritty.yml" "/home/taskylizard/.config/alacritty/alacritty.yml"
handle_file_ln "/home/taskylizard/.dotfiles/config/catgirl/aliucord.conf" "/home/taskylizard/.config/catgirl/aliucord.conf"
handle_file_ln "/home/taskylizard/.dotfiles/config/flameshot/flameshot.conf" "/home/taskylizard/.config/flameshot/flameshot.conf"
handle_file_ln "/home/taskylizard/.dotfiles/config/i3/config" "/home/taskylizard/.config/i3/config"
handle_file_ln "/home/taskylizard/.dotfiles/config/i3/i3blocks.conf" "/home/taskylizard/.config/i3/i3blocks.conf"
handle_file_ln "/home/taskylizard/.dotfiles/config/i3/toggletouchpad.sh" "/home/taskylizard/.config/i3/toggletouchpad.sh"
handle_file_ln "/home/taskylizard/.dotfiles/config/i3status/config" "/home/taskylizard/.config/i3status/config"
handle_file_ln "/home/taskylizard/.dotfiles/config/neofetch/config.conf" "/home/taskylizard/.config/neofetch/config.conf"
handle_file_ln "/home/taskylizard/.dotfiles/config/nvim/coc-settings.json" "/home/taskylizard/.config/nvim/coc-settings.json"
handle_file_ln "/home/taskylizard/.dotfiles/config/nvim/colors/zen.lua" "/home/taskylizard/.config/nvim/colors/zen.lua"
handle_file_ln "/home/taskylizard/.dotfiles/config/nvim/core/keybinds.vim" "/home/taskylizard/.config/nvim/core/keybinds.vim"
handle_file_ln "/home/taskylizard/.dotfiles/config/nvim/core/plugsettings.vim" "/home/taskylizard/.config/nvim/core/plugsettings.vim"
handle_file_ln "/home/taskylizard/.dotfiles/config/nvim/core/settings.vim" "/home/taskylizard/.config/nvim/core/settings.vim"
handle_file_ln "/home/taskylizard/.dotfiles/config/nvim/init.lua" "/home/taskylizard/.config/nvim/init.lua"
handle_file_ln "/home/taskylizard/.dotfiles/config/nvim/lua/keybinds.lua" "/home/taskylizard/.config/nvim/lua/keybinds.lua"
handle_file_ln "/home/taskylizard/.dotfiles/config/nvim/lua/plugins.lua" "/home/taskylizard/.config/nvim/lua/plugins.lua"
handle_file_ln "/home/taskylizard/.dotfiles/config/nvim/lua/pluginsettings.lua" "/home/taskylizard/.config/nvim/lua/pluginsettings.lua"
handle_file_ln "/home/taskylizard/.dotfiles/config/nvim/lua/settings.lua" "/home/taskylizard/.config/nvim/lua/settings.lua"
handle_file_ln "/home/taskylizard/.dotfiles/config/nvim/lua/statusline.lua" "/home/taskylizard/.config/nvim/lua/statusline.lua"
handle_file_ln "/home/taskylizard/.dotfiles/config/nvim/lua/themer/color_schemes/zen.lua" "/home/taskylizard/.config/nvim/lua/themer/color_schemes/zen.lua"
handle_file_ln "/home/taskylizard/.dotfiles/config/nvim-qt/window-geometry.conf" "/home/taskylizard/.config/nvim-qt/window-geometry.conf"
handle_file_ln "/home/taskylizard/.dotfiles/config/picom/picom.conf" "/home/taskylizard/.config/picom/picom.conf"
handle_file_ln "/home/taskylizard/.dotfiles/config/rofi/Arc-Dark.rasi" "/home/taskylizard/.config/rofi/Arc-Dark.rasi"
handle_file_ln "/home/taskylizard/.dotfiles/config/rofi/config" "/home/taskylizard/.config/rofi/config"
handle_file_ln "/home/taskylizard/.dotfiles/config/xplr/core/general.lua" "/home/taskylizard/.config/xplr/core/general.lua"
handle_file_ln "/home/taskylizard/.dotfiles/config/xplr/core/init.lua" "/home/taskylizard/.config/xplr/core/init.lua"
handle_file_ln "/home/taskylizard/.dotfiles/config/xplr/init.lua" "/home/taskylizard/.config/xplr/init.lua"
handle_file_ln "/home/taskylizard/.dotfiles/config/zentile/config.toml" "/home/taskylizard/.config/zentile/config.toml"
handle_file_ln "/home/taskylizard/.dotfiles/install.sh" "/home/taskylizard/.install.sh"
handle_file_ln "/home/taskylizard/.dotfiles/zshrc" "/home/taskylizard/.zshrc"
