gui:
  showIcons: true
  branchColors:
    "trunk": "#7AA2F7"
  authorColors:
    "taskylizard": "#bb9af7"
  theme:
    activeBorderColor:
      - "#9ECE6A"
      - bold
    inactiveBorderColor:
      - "#C0CAF5"
    optionsTextColor:
      - "#535D84"
    defaultFgColor:
      - "#B1BAE6"
    selectedLineBgColor:
      - default
    selectedRangeBgColor:
      - default

customCommands:
  - key: "<c-P>"
    description: "Push to a specific remote repository"
    context: "global"
    loadingText: "Pushing ..."
    prompts:
      - type: "menuFromCommand"
        title: "Which remote repository to push to?"
        command: bash -c "git remote --verbose | grep '/.* (push)'"
        filter: '(?P<remote>.*)\s+(?P<url>.*) \(push\)'
        valueFormat: "{{ .remote }}"
        labelFormat: "{{ .remote | bold | cyan }} {{ .url }}"
      - type: "menu"
        title: "How to push?"
        options:
          - value: "push"
          - value: "push --force-with-lease"
          - value: "push --force"
  - key: "<c-p>"
    context: "global"
    loadingText: "pushing"
    prompts:
      - type: "input"
        title: "which branch do you want to push to?"
    command: "git push origin {{index .PromptResponses 0}}"
  - key: "P"
    command: "git push {{.SelectedRemote.RefName}} {{.SelectedLocalCommit.Sha}}:{{.SelectedLocalBranch.RefName}}"
    context: "commits"
    loadingText: "Pushing commit..."
    description: "Push a specific commit (and any preceding)"
    stream: yes
  - key: "<c-r>"
    command: "gh pr create --fill --web"
    context: "global"
    loadingText: "Creating pull request on GitHub"

os:
  editCommand: "nvim"

git:
  overrideGpg: true
  commitPrefixes:
    fidelity: # This is repository folder name
      pattern: "^\\w+\\/(\\w+-\\w+).*"
      replace: "[$1] "
