return {
  -- LSP
  ActiveLSP = "",
  ActiveTS = "",
  LSPLoaded = "",
  LSPLoading1 = "⠋",
  LSPLoading2 = "⠙",
  LSPLoading3 = "⠹",
  LSPLoading4 = "⠸",
  LSPLoading5 = "⠼",
  LSPLoading6 = "⠴",
  LSPLoading7 = "⠦",
  LSPLoading8 = "⠧",
  LSPLoading9 = "⠇",
  LSPLoading10 = "⠏",
  -- Git
  Git = "",
  GitAdd = "",
  GitBranch = "",
  GitChange = "",
  GitConflict = "",
  GitDelete = "",
  GitIgnored = "",
  GitRenamed = "",
  GitStaged = "✓",
  GitUnstaged = "✗",
  GitUntracked = "★",
  -- Files
  Ellipsis = "",
  DefaultFile = "",
  FileModified = "",
  FileReadOnly = "",
  FoldClosed = "",
  FoldOpened = "",
  FolderClosed = "",
  FolderEmpty = "",
  FolderOpen = "",
  -- DAP
  DapBreakpoint = "",
  DapBreakpointCondition = "",
  DapBreakpointRejected = "",
  DapLogPoint = "",
  DapStopped = "",
  -- Diagnostics
  Diagnostic = "󰒡",
  DiagnosticError = "",
  DiagnosticHint = "",
  DiagnosticInfo = "󰋼",
  DiagnosticWarn = "",
  -- Misc
  FileEncoding = "",
  ScrollText = "",
  TabWidth = "",
}
