"$schema" = 'https://starship.rs/config-schema.json'

format = """
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$package\
$python\
$crystal\
$custom\
$sudo\
$line_break\
$jobs\
$status\
$shell\
$character"""

command_timeout = 100
add_newline = true

[character]
success_symbol = '[λ](bold green)'
error_symbol = "[λ](bold red)"

[directory]
format = "[$path](bold $style)[$read_only]($read_only_style) "
style = "bold #ffafff"
read_only = ""
read_only_style = "bold red"

[crystal]
symbol = " "
format = "via [$symbol ($version)](bold purple) "
